language: node_js

node_js:
  - "7"

cache: npm

sudo: false

script:
  - npm run test:ci

after_success:
  - codecov

before_deploy:
  - npm run build
  - cp ./build/index.html ./build/200.html

deploy:
  provider: surge
  project: ./build/
  domain: cra-test.surge.sh
  skip_cleanup: true